# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    ports:
      - "5000:5000"
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
#      args:
#        ARG: <ARG>
#    image: ift6758/serving:<TAG>

  jupyter:
    build:
      context: ./
      dockerfile: ./Dockerfile.jupyter
#      args:
#        ARG: <ARG>
#    image: ift6758/jupyter:<TAG>
    ports:
      - "3000:3000"
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
      

     
